import axios from "axios";

const BACKEND_URL = 'https://expenses-a8c71-default-rtdb.firebaseio.com'

export async function storeExpense(expenseData) {
    const response = await axios.post( BACKEND_URL + '/expenses.json', expenseData );
    const id = response.data.name;  // get id that auto generated by firebase when I post
    return id;
} 

export async function fetchExpenses() {
    const response = await axios.get( BACKEND_URL + '/expenses.json');

    const expanses = [];

    for (const key in response.data) {
        const expenseObj = {
            id: key,
            amount: response.data[key].amount,
            date: new Date(response.data[key].date),
            description: response.data[key].description
        }
        expanses.push(expenseObj)
    }
    return expanses
}